[package]
name = "plonky2-recursion-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use a stable plonky2 release; adjust version as needed
plonky2 = "1.1.0"
serde = { version = "1.0", features = ["derive"] }